version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - '9000:9000'
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    # TODO: persist data
  composer:
    build:
      context: .
      dockerfile: ./composer/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  artisan:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ['php', '/var/www/html/artisan']
  yarn:
    build:
      context: ./
      dockerfile: ./yarn/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ['yarn']
