version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: <username>
    #   MONGO_INITDB_ROOT_PASSWORD: <password>
    #   MONGO_INITDB_DATABASE: <database>
    env_file:
      - .env
    # networks: can be automatically created by docker-compose if they don't exist
    # networks:
    #   - <network_name>
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     - <key>=<value>
    container_name: backend
    restart: always
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    # networks:
    #   - <network_name>
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      # - ./frontend/src:/app/src
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    # env_file:
    #   - ./frontend/.env
    depends_on:
      - backend
    # networks:
    #   - <network_name>

# named volumes need to be specified in the top level
volumes:
  data:
  logs:
